//
// Created by Oz Zafar on 20/05/2020.
//

#ifndef CPP_STOWAGE_CHECKALGORITHMERROR_H
#define CPP_STOWAGE_CHECKALGORITHMERROR_H

#include "string"


class CheckAlgorithmError {
public:
    enum Error {
        FULL_CONTAINER_POSITION,
        UNLOAD_NOT_TOP_CONTAINER,
        LOADED_PORT_DESTINATION_IS_CURRENT_PORT,
        CONTAINER_DESTINATION_ISNT_IN_NEXT_STOPS,
        REJECTED_NOT_FAR_CONTAINERS,
        BAD_CONTAINER_WASNT_REJECTED,
        CONTAINER_WASNT_REVIEWED,
        SHIP_ISNT_EMPTY_IN_END_OF_TRAVEL,
        CONTAINERS_SHOULD_BE_UNLOADED_SKIPPED_BY_THE_ALGORITHM,
        CONTAINERS_ON_PORT_IGNORED_BY_THE_ALGORITHM,
        CONTAINER_INCORRECTLY_REJECTED,
        SHIP_HAS_CONTAINERS_AT_THE_END_OF_THE_ROUTE,
        FAILED_TO_LOAD_ALGORITHM
    };

    std::string errorToString(Error error);
};


#endif //CPP_STOWAGE_CHECKALGORITHMERROR_H
